/**************************************************************************************************
 *
 *  Class:   
 *
 *  @description : This class contains unit tests for validating behavior of PurchasedAccountCSVUtil
 *  @author : A5E Consulting
 *  @date : 10/09/2016
 * 
 *************************************************************************************************/
 
@isTest
private class TestPurchasedAccountCSVUtil{

}