name: scan-delta-code
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  apex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install SFDX CLI and Scanner anf SFDX Delta
      run: |
        npm install sfdx-cli -g
        sfdx plugins:install @salesforce/sfdx-scanner
        
    - name: "Installing sfdx git delta"
      run: |
        echo y | sfdx plugins:install sfdx-git-delta
        sfdx plugins

    - name: "Create delta packages for new, modified or deleted metadata"
      run: |
        mkdir changed-sources
        sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/

    - name: Setup PMD
      uses: legetz/setup-pmd@7.1.0

    - name: APEX full scan for design rules only
      run: pmd check --dir changed-sources/force-app/main/default/classes -R apex_ruleset.xml -f text