name: scan-delta-code
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  apex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: APEX delta scan
      uses: mitchspano/sfdx-scan-pull-request@v0.1.16
      with:
        pmdconfig: pmd-rules.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}